<?php
/**
 * Created by IntelliJ IDEA.
 * User: canerkavak
 * Date: 13.11.2018
 * Time: 20:18
 */

class GuessModel extends CI_Model
{

    private $table = "guess_new";

    public function __construct() {

        parent::__construct();
        $this->load->database();

    }
	public function insert($array_data){
		return $this->db->insert($this->table,$array_data);
	}

	public function getAll(){
		return $this->db->select("*")->from($this->table)->get()->result();
	}

	public function getById($id){
		return $this->db->select("*")->from($this->table)->where("id",$id)->get()->result();
	}

	public function update($array_data,$id){
		/*    	print_r($array_data);*/
		$this->db->where("id",$id);
		$this->db->update($this->table,$array_data);
	}

	public function delete($id){
		$this->db->where('id', $id);
		$this->db->delete($this->table);
	}

	public function getImageNames(){
        return array(
            "Afghanistan"=>"Afghanistan",
            "Albania"=>"Albania",
            "Algeria"=>"Algeria",
            "Andorra"=>"Andorra",
            "Angola"=>"Angola",
            "Antarctica"=>"Antarctica",
            "Antigua-and-barbuda."=>"Antigua-and-barbuda.",
            "Argentina"=>"Argentina",
            "Armania"=>"Armania",
            "Aruba"=>"Aruba",
            "Australia"=>"Australia",
            "Austria"=>"Austria",
            "Azerbaijan"=>"Azerbaijan",
            "Bahrain"=>"Bahrain",
            "Bangladesh"=>"Bangladesh",
            "Barbados"=>"Barbados",
            "Belarus"=>"Belarus",
            "Belguim"=>"Belguim",
            "Belize"=>"Belize",
            "Benin"=>"Benin",
            "Bhutan"=>"Bhutan",
            "Bolivia"=>"Bolivia",
            "Bosnia-and-Herzegovina"=>"Bosnia-and-Herzegovina",
            "Botswana"=>"Botswana",
            "Brazil"=>"Brazil",
            "Brunei"=>"Brunei",
            "Bulgaria"=>"Bulgaria",
            "Burkina-Faso"=>"Burkina-Faso",
            "Burundi"=>"Burundi",
            "Camaroon"=>"Camaroon",
            "Cambodia"=>"Cambodia",
            "Canada"=>"Canada",
            "Cape-Verde"=>"Cape-Verde",
            "Catalonia"=>"Catalonia",
            "Central-African-Republic"=>"Central-African-Republic",
            "Chad"=>"Chad",
            "Chile"=>"Chile",
            "China"=>"China",
            "Colombia"=>"Colombia",
            "Comoros"=>"Comoros",
            "Costa-rica"=>"Costa-rica",
            "Cote-dIvoire"=>"Cote-dIvoire",
            "Croatia"=>"Croatia",
            "Cuba"=>"Cuba",
            "Cyprus"=>"Cyprus",
            "Czech-Republic"=>"Czech-Republic",
            "Democratic-Republic-of-the-Congo"=>"Democratic-Republic-of-the-Congo",
            "Denmark"=>"Denmark",
            "Djibouti"=>"Djibouti",
            "Dominica"=>"Dominica",
            "Dominican-Republic"=>"Dominican-Republic",
            "Ecuador"=>"Ecuador",
            "Egypt"=>"Egypt",
            "El-Salvador"=>"El-Salvador",
            "England"=>"England",
            "Equatorial-Guinea"=>"Equatorial-Guinea",
            "Eritera"=>"Eritera",
            "Estonia"=>"Estonia",
            "Ethiopia"=>"Ethiopia",
            "European-Union"=>"European-Union",
            "Faroes"=>"Faroes",
            "Fiji"=>"Fiji",
            "Finland"=>"Finland",
            "France"=>"France",
            "Gabon"=>"Gabon",
            "Georgia"=>"Georgia",
            "Germany"=>"Germany",
            "Ghana"=>"Ghana",
            "Gibrlater"=>"Gibrlater",
            "Greece"=>"Greece",
            "Greenland"=>"Greenland",
            "Grenada"=>"Grenada",
            "Guatemala"=>"Guatemala",
            "Guinea"=>"Guinea",
            "Guinea-bissau"=>"Guinea-bissau",
            "Guyana"=>"Guyana",
            "Haiti"=>"Haiti",
            "Honduras"=>"Honduras",
            "Hong-Kong"=>"Hong-Kong",
            "Hungary"=>"Hungary",
            "Iceland"=>"Iceland",
            "India"=>"India",
            "Indonisia"=>"Indonisia",
            "Iran"=>"Iran",
            "Iraq"=>"Iraq",
            "Ireland"=>"Ireland",
            "Israel"=>"Israel",
            "Italy"=>"Italy",
            "Jamaica"=>"Jamaica",
            "Japan"=>"Japan",
            "Jordan"=>"Jordan",
            "Kazakhstan"=>"Kazakhstan",
            "Kenya"=>"Kenya",
            "Kiribati"=>"Kiribati",
            "Kuwait"=>"Kuwait",
            "Kyrgyzstan"=>"Kyrgyzstan",
            "Laos"=>"Laos",
            "Latvia"=>"Latvia",
            "Lebanon"=>"Lebanon",
            "Lesotho"=>"Lesotho",
            "Liberia"=>"Liberia",
            "Libya"=>"Libya",
            "Liechtenstein"=>"Liechtenstein",
            "Lithuania"=>"Lithuania",
            "Luxemburg"=>"Luxemburg",
            "Lybia"=>"Lybia",
            "Macau"=>"Macau",
            "Macedonia"=>"Macedonia",
            "Madagascar"=>"Madagascar",
            "Malawi"=>"Malawi",
            "Malaysia"=>"Malaysia",
            "Maldives"=>"Maldives",
            "Mali"=>"Mali",
            "Malta"=>"Malta",
            "Mamibia"=>"Mamibia",
            "Marshall-Islands"=>"Marshall-Islands",
            "Mauritania"=>"Mauritania",
            "Mauritius"=>"Mauritius",
            "Mexico"=>"Mexico",
            "Micronesia"=>"Micronesia",
            "Moldova"=>"Moldova",
            "Monaco"=>"Monaco",
            "Mongolia"=>"Mongolia",
            "Monternegro"=>"Monternegro",
            "Morocco"=>"Morocco",
            "Mozambique"=>"Mozambique",
            "Myanmar"=>"Myanmar",
            "Nauru"=>"Nauru",
            "Nepal"=>"Nepal",
            "Netherlands"=>"Netherlands",
            "New-zealand"=>"New-zealand",
            "Nicaragua"=>"Nicaragua",
            "Niger"=>"Niger",
            "Nigeria"=>"Nigeria",
            "Northen-Ireland"=>"Northen-Ireland",
            "North-Korea"=>"North-Korea",
            "Norway"=>"Norway",
            "Oman"=>"Oman",
            "Pakistan"=>"Pakistan",
            "Palau"=>"Palau",
            "Palestine"=>"Palestine",
            "Panama"=>"Panama",
            "Papua-New-Guinea"=>"Papua-New-Guinea",
            "Paraguay"=>"Paraguay",
            "Peru"=>"Peru",
            "Philippines"=>"Philippines",
            "Poland"=>"Poland",
            "Portugal"=>"Portugal",
            "Puerto-Rico"=>"Puerto-Rico",
            "Quatar"=>"Quatar",
            "Republic-of-the-Congo"=>"Republic-of-the-Congo",
            "Romania"=>"Romania",
            "Russia"=>"Russia",
            "Rwanda"=>"Rwanda",
            "Saint-Kitts-and-Nevis"=>"Saint-Kitts-and-Nevis",
            "Saint-Lucia"=>"Saint-Lucia",
            "Saint-Vincent-and-the-Grenadines"=>"Saint-Vincent-and-the-Grenadines",
            "Samoa"=>"Samoa",
            "San-Marino"=>"San-Marino",
            "Sao-Tome-and-Principe"=>"Sao-Tome-and-Principe",
            "Saudi-Arabia"=>"Saudi-Arabia",
            "Scotland"=>"Scotland",
            "Senegal"=>"Senegal",
            "Serbia"=>"Serbia",
            "Seychelles"=>"Seychelles",
            "Sierra-Leone"=>"Sierra-Leone",
            "Singapore"=>"Singapore",
            "Slovakia"=>"Slovakia",
            "Slovenia"=>"Slovenia",
            "Solomon-islands"=>"Solomon-islands",
            "Somalia"=>"Somalia",
            "South-africa"=>"South-africa",
            "South-korea"=>"South-korea",
            "South-Sudan"=>"South-Sudan",
            "Spain"=>"Spain",
            "Sri-Lanka"=>"Sri-Lanka",
            "Sudan"=>"Sudan",
            "Suriname"=>"Suriname",
            "Swaziland"=>"Swaziland",
            "Sweden"=>"Sweden",
            "Switzerland"=>"Switzerland",
            "Syria"=>"Syria",
            "Taiwan"=>"Taiwan",
            "Tajikistan"=>"Tajikistan",
            "Tanzania"=>"Tanzania",
            "Thailand"=>"Thailand",
            "The-Bahamas"=>"The-Bahamas",
            "The-Gambia"=>"The-Gambia",
            "Timor-Leste"=>"Timor-Leste",
            "Togo"=>"Togo",
            "Tonga"=>"Tonga",
            "Trinidad-and-Tobago"=>"Trinidad-and-Tobago",
            "Tunisia"=>"Tunisia",
            "Turkey"=>"Turkey",
            "Turkmenistan"=>"Turkmenistan",
            "Tuvalu"=>"Tuvalu",
            "uefa-avrupa"=>"uefa-avrupa",
            "uefa-sampiyonlar"=>"uefa-sampiyonlar",
            "Uganda"=>"Uganda",
            "Ukraine"=>"Ukraine",
            "United-Arab-Emirates"=>"United-Arab-Emirates",
            "United-Kingdom"=>"United-Kingdom",
            "United-Nations"=>"United-Nations",
            "United-States"=>"United-States",
            "Unknown"=>"Unknown",
            "Uruguay"=>"Uruguay",
            "Uzbekistan"=>"Uzbekistan",
            "Vanatu"=>"Vanatu",
            "Vatican-City"=>"Vatican-City",
            "Venezuela"=>"Venezuela",
            "Vietnam"=>"Vietnam",
            "Wales"=>"Wales",
            "Western-Sahara"=>"Western-Sahara",
            "Yemen"=>"Yemen",
            "Zambia"=>"Zambia",
            "Zimbabwe"=>"Zimbabwe");

    }
}
